filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /tmp/go_logs/*.log
  json.add_error_key: true

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["192.168.50.234:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "192.168.50.234:5601"